name: 向 GitHub Page 部署静态内容

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/deploy.yaml"
      - "src/"
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Page
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一次并发部署，跳过正在进行的运行和最新排队的运行之间的排队运行。
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 单个部署任务，因为我们只是部署
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 签出
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 设置 Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: latest

      - name: 安装依赖
        shell: bash
        run: npm ci

      - name: 构建项目
        shell: bash
        run: npm run build

      - name: 设置页面
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: 上传工件
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: "src/"

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
