name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: 设置 pnpm 和 Node.js
        uses: pnpm/setup@e0ed22ae4d909f13ed5d2688513f73e1875e46db # v3.0.0
        with:
          runtime: "node@latest"
          install: true
          require-lockfile: true

      - name: 运行 lint
        shell: bash
        run: |-
          pnpm run lint
